name: Merge Hive Test
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Nethermind
        uses: actions/checkout@v2
        with: 
          repository: 'NethermindEth/nethermind'
      - name: Unshallow fetching
        run: git fetch --unshallow
      - run: mkdir image
      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setting up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Building Nethermind Image
        run: |
          docker buildx build --platform=linux/amd64 -o type=local,dest=image -t nethermind:test --build-arg GIT_COMMIT=$(git log -1 --format=%h) .
      - name: test
        run: |
         cd image/linux_amd64
         ls
         
