        description: 'Limit for hive tests'
        required: false
        type: string
      branch:
        description: 'Branch for hive tests'
        default: 'master'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      testSuite:
        description: 'Test suite'
        required: true
        default: 'ethereum/engine' 
        type: choice
        options:
        - ethereum/engine        
        - ethereum/rpc
        - devp2p
        - ethereum/graphql
        - ethereum/consensus
      hive:
        description: 'Repository for hive tests'
        required: true
        default: 'ethereum/hive'
        type: string
      limit:
        description: 'Limit for hive tests'
        required: false
        type: string        
      branch:
        description: 'Branch for hive tests'
        default: 'master'
        required: false
        type: string

jobs:
  build-dockers:
	@@ -57,27 +67,28 @@
        run: git fetch --unshallow
      - name: Setting up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Building Nethermind Image
        uses: docker/build-push-action@v2
        with: 
          context: .
          file: ./Dockerfile
          tags: nethermind:test-${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar
      - name: Installing Linux packages
        run: |
         sudo apt-get update
         sudo apt-get install libsnappy-dev libc6-dev libc6 build-essential
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
         go-version: '>=1.17.0'
      - name: Check out Hive
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.hive }}
          ref: ${{ github.event.inputs.branch }}
      - name: Change Hive configuration
        run: sed -i 's#FROM nethermindeth/hive:$branch#FROM nethermind:test-${{ github.sha }}#g' clients/nethermind/Dockerfile
      - name: Build Hive
