      - name: Upload Docker Image
        uses: actions/upload-artifact@v3
        with:
          name: nethermind
          path: image
      - name: Check out Hive
        uses: actions/checkout@v2
        with:
          repository: 'DockBoss/hive'
      - name: Download Docker Image
        uses: actions/download-artifact@v3
        with:
          name: nethermind
          path: image
      - name: test
        run: |
         ls
         cd ..
         ls